# Generated by Django 5.2.8 on 2025-12-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='chombo_enabled',
            field=models.BooleanField(default=True, help_text='Enable chombo penalty (-30 points)'),
        ),
        migrations.AddField(
            model_name='team',
            name='uma_first',
            field=models.IntegerField(default=15, help_text='Uma bonus for 1st place'),
        ),
        migrations.AddField(
            model_name='team',
            name='uma_fourth',
            field=models.IntegerField(default=-15, help_text='Uma bonus for 4th place'),
        ),
        migrations.AddField(
            model_name='team',
            name='uma_second',
            field=models.IntegerField(default=5, help_text='Uma bonus for 2nd place'),
        ),
        migrations.AddField(
            model_name='team',
            name='uma_third',
            field=models.IntegerField(default=-5, help_text='Uma bonus for 3rd place'),
        ),
    ]
