# Generated by Django 5.2.8 on 2025-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_chombo_enabled_team_uma_first_team_uma_fourth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='start_point',
            field=models.IntegerField(default=30000, help_text='Starting chips for each player'),
        ),
        migrations.AddField(
            model_name='team',
            name='target_point',
            field=models.IntegerField(default=30000, help_text='Target score for calculating base points'),
        ),
    ]
