# Generated by Django 5.2.8 on 2026-01-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_add_start_and_target_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide team from public team list'),
        ),
    ]
