# Generated by Django 5.2.8 on 2026-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_add_hidden_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='member',
            name='teams_membe_team_id_691fb1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='member',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='If set, shown instead of name in standings tables', max_length=100),
        ),
    ]
