# Generated by Django 5.2.8 on 2026-07-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_add_member_display_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('team', 'name')},
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['team', 'name'], name='teams_membe_team_id_691fb1_idx'),
        ),
    ]
