# Generated by Django 5.2.8 on 2026-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='chombo_penalty',
            field=models.IntegerField(default=30000, help_text='Raw score penalty per chombo (default 30000 = -30 pts after ÷1000)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='chombo_enabled',
            field=models.BooleanField(default=True, help_text='Enable chombo penalty'),
        ),
    ]
