# Generated by Django 5.2.8 on 2025-11-30 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('average_per_game', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_score', to='teams.member')),
            ],
            options={
                'verbose_name': 'Calculated Score',
                'verbose_name_plural': 'Calculated Scores',
            },
        ),
        migrations.CreateModel(
            name='RawScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_scores', to='teams.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'session_id'], name='scores_raws_member__e2f458_idx'), models.Index(fields=['session_id'], name='scores_raws_session_61e10d_idx')],
                'unique_together': {('member', 'session_id')},
            },
        ),
    ]
