# Generated by Django 5.2.8 on 2025-11-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawscore',
            name='chombo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calculatedscore',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
