# Generated by Django 5.2.8 on 2025-12-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_rawscore_chombo_alter_calculatedscore_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawscore',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
