# Generated by Django 5.2.8 on 2025-12-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_rawscore_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawscore',
            name='placement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
