# Generated by Django 5.2.8 on 2025-12-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_rawscore_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedscore',
            name='average_placement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='calculatedscore',
            name='chombo_count',
            field=models.IntegerField(default=0),
        ),
    ]
