# Generated by Django 5.2.8 on 2025-12-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_calculatedscore_average_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawscore',
            name='chombo',
            field=models.IntegerField(default=0),
        ),
    ]
