# Generated by Django 5.2.8 on 2025-12-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_change_chombo_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedscore',
            name='first_place_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculatedscore',
            name='fourth_place_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculatedscore',
            name='second_place_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculatedscore',
            name='third_place_count',
            field=models.IntegerField(default=0),
        ),
    ]
