# Generated by Django 5.2.8 on 2025-12-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_add_placement_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawscore',
            name='placement',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
