# Generated by Django 5.2.8 on 2026-01-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_change_placement_to_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawscore',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
