# Generated by Django 5.2.8 on 2026-07-31 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0008_player_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('start_point', models.IntegerField(default=30000)),
                ('target_point', models.IntegerField(default=30000)),
                ('uma_first', models.IntegerField(default=15)),
                ('uma_second', models.IntegerField(default=5)),
                ('uma_third', models.IntegerField(default=-5)),
                ('uma_fourth', models.IntegerField(default=-15)),
                ('chombo_enabled', models.BooleanField(default=True)),
                ('session_mode', models.CharField(choices=[('fixed', 'Fixed pairings'), ('rank', 'Rank-based (Swiss-style)'), ('hybrid', 'Hybrid (fixed then rank-based)')], default='fixed', max_length=10)),
                ('fixed_hanchan_count', models.PositiveIntegerField(default=3, help_text='Number of hanchans with fixed pairings (also used as total for rank-only mode)')),
                ('rank_hanchan_count', models.PositiveIntegerField(default=0, help_text='Additional rank-based hanchans (hybrid mode) or total hanchans (rank-only mode)')),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('sessions_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_substitute', models.BooleanField(default=False, help_text='Substitutes play in sessions but are excluded from standings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_memberships', to='teams.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='taikai.tournament')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMemberTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0)),
                ('games_played', models.IntegerField(default=0)),
                ('average_per_game', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_score', to='taikai.tournamentmember')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hanchan_number', models.PositiveIntegerField()),
                ('table_number', models.PositiveIntegerField()),
                ('generation_type', models.CharField(choices=[('fixed', 'Fixed'), ('rank', 'Rank-based')], max_length=10)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='taikai.tournament')),
            ],
            options={
                'ordering': ['order_index', 'hanchan_number', 'table_number'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TournamentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='taikai.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='TournamentSessionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('placement', models.FloatField(blank=True, null=True)),
                ('chombo', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_scores', to='taikai.tournamentmember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='taikai.tournamentsession')),
            ],
            options={
                'unique_together': {('session', 'member')},
            },
        ),
    ]
