# Generated by Django 5.2.8 on 2026-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikai', '0006_recalculate_tournament_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='chombo_penalty',
            field=models.IntegerField(default=30000, help_text='Raw score penalty per chombo (default 30000 = -30 pts after ÷1000)'),
        ),
        migrations.AlterField(
            model_name='tournamentsession',
            name='generation_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('rank', 'Rank-based'), ('manual', 'Manual')], max_length=10),
        ),
    ]
