# Generated by Django 5.2.8 on 2026-08-16 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikai', '0007_add_chombo_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finals_cutoff',
            field=models.PositiveIntegerField(blank=True, help_text='Top N players in finals after cutoff is applied (must be divisible by 4)', null=True),
        ),
        migrations.AddField(
            model_name='tournamentmember',
            name='in_finals',
            field=models.BooleanField(default=False, help_text='Included in the post-cutoff finals group'),
        ),
        migrations.CreateModel(
            name='TournamentMemberFinalsTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0)),
                ('games_played', models.IntegerField(default=0)),
                ('average_per_game', models.FloatField(default=0.0)),
                ('average_placement', models.FloatField(default=0.0)),
                ('chombo_count', models.IntegerField(default=0)),
                ('first_place_count', models.IntegerField(default=0)),
                ('second_place_count', models.IntegerField(default=0)),
                ('third_place_count', models.IntegerField(default=0)),
                ('fourth_place_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finals_total_score', to='taikai.tournamentmember')),
            ],
        ),
    ]
