# Generated by Django 5.2.8 on 2026-08-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikai', '0008_finals_cutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finals_start_order_index',
            field=models.IntegerField(blank=True, help_text='Sessions at or below this order_index do not count toward finals standings', null=True),
        ),
    ]
